name: Server image push to acr

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Build
      uses: bulletsman04/acr-task-github-action@84ca53c
      with:
        # Service Principal with Contributor role on the ACR
        service_principal: ${{ secrets.ACR_SP_NAME }}
        # Service Principal password
        service_principal_password: ${{ secrets.ACR_SP }}
        # Azure Container Registry tenant
        tenant: ${{ secrets.ACR_TENANT }}
        # The name of the ACR, minus the .azurecr.io
        registry: ${{ secrets.ACR_NAME }}
        # Repository to use
        repository: server
        # Docker image tag, default to the commit SHA
        tag: latest
        # Branch to build from, defaults to master
        branch: github-actions
        # The folder in the Github repo that holds the source
        folder: Server/BetterPointingPoker.Server.Web
